"""Structured version of docs/PS_TRACEABILITY_MATRIX.md, served via the API
so the mapping from PS-26159 requirement -> implementation -> API -> UI ->
evidence is verifiable from the running system itself, not just a doc that
can drift out of sync with the code. Keep this in lockstep with the doc
when either changes.
"""

PS_TRACEABILITY_MATRIX = [
    {"id": 1, "outcome": "SMTP identification", "feature": "Port/banner-based protocol detection",
     "api": "POST /api/cases/upload (background analysis)", "ui": "Case Detail -> Session Inventory",
     "tests": "tests/test_pcap_corpus_e2e.py"},
    {"id": 2, "outcome": "IMAP identification", "feature": "Same engine, IMAP ports/banner",
     "api": "GET /api/cases/{id}/sessions", "ui": "Case Detail -> Session Inventory",
     "tests": "tests/test_pcap_corpus_e2e.py"},
    {"id": 3, "outcome": "POP3 identification", "feature": "Same engine, POP3 ports/banner",
     "api": "GET /api/cases/{id}/sessions", "ui": "Case Detail -> Session Inventory",
     "tests": "tests/test_pcap_corpus_e2e.py"},
    {"id": 4, "outcome": "STARTTLS negotiation detection & validation",
     "feature": "analyze_stream_tls() STARTTLS command/response correlation",
     "api": "GET /api/cases/{id}/sessions (starttls_used, starttls_success)",
     "ui": "Session detail -> Encryption panel", "tests": "tests/test_stream_reassembly.py"},
    {"id": 5, "outcome": "Complete TCP stream reconstruction",
     "feature": "StreamBuffer: seq-aware reorder/dedup/overlap-trim/gap tracking; FIN/RST state",
     "api": "GET /api/cases/{id}/sessions (reassembly_gaps, tcp_connection_state)",
     "ui": "Session detail -> Connection state badge", "tests": "tests/test_stream_reassembly.py"},
    {"id": 6, "outcome": "TLS handshake reconstruction",
     "feature": "_parse_handshake_messages() cross-record reassembly",
     "api": "GET /api/cases/{id}/sessions", "ui": "Session detail", "tests": "tests/test_stream_reassembly.py"},
    {"id": 7, "outcome": "Negotiated TLS versions", "feature": "ClientHello/ServerHello version parsing",
     "api": "sessions[].tls_version", "ui": "Session detail", "tests": "tests/test_pcap_corpus_e2e.py"},
    {"id": 8, "outcome": "Negotiated cipher suites",
     "feature": "ServerHello cipher parsing against crypto_reference.py IANA registry",
     "api": "sessions[].cipher_suite", "ui": "Session detail", "tests": "tests/test_crypto_reference.py"},
    {"id": 9, "outcome": "Key-exchange mechanisms",
     "feature": "TLS1.3 key_share / TLS<=1.2 cipher-implied KEX extraction",
     "api": "sessions[].key_exchange", "ui": "Session detail", "tests": "tests/test_crypto_reference.py"},
    {"id": 10, "outcome": "X.509 extraction",
     "feature": "analyze_certificate() (subject/issuer/validity/key/sig/fingerprint)",
     "api": "sessions[].cert_*", "ui": "Session detail -> Certificate panel",
     "tests": "tests/test_cert_chain_validation.py"},
    {"id": 11, "outcome": "Certificate-chain validation",
     "feature": "validate_certificate_chain() -- signature verification against Mozilla root store, "
                "plus TLS1.3 observability model",
     "api": "sessions[].cert_chain_valid, cert_observable, observability_note",
     "ui": "Session detail (suppressed/relabeled for TLS1.3)",
     "tests": "tests/test_cert_chain_validation.py, tests/test_upgrade3_additions.py"},
    {"id": 12, "outcome": "Certificate expiration", "feature": "analyze_certificate() validity window check",
     "api": "sessions[].cert_expired", "ui": "Session detail", "tests": "tests/test_cert_chain_validation.py"},
    {"id": 13, "outcome": "Public-key algorithm", "feature": "analyze_certificate()",
     "api": "sessions[].cert_key_algo", "ui": "Session detail", "tests": "tests/test_cert_chain_validation.py"},
    {"id": 14, "outcome": "Public-key length", "feature": "analyze_certificate()",
     "api": "sessions[].cert_key_size", "ui": "Session detail", "tests": "tests/test_cert_chain_validation.py"},
    {"id": 15, "outcome": "Digital signature algorithm", "feature": "analyze_certificate()",
     "api": "sessions[].cert_sig_algo", "ui": "Session detail", "tests": "tests/test_cert_chain_validation.py"},
    {"id": 16, "outcome": "Weak crypto / deprecated TLS detection",
     "feature": "findings_engine.py rule engine against crypto_reference.py",
     "api": "GET /api/cases/{id}/findings", "ui": "Findings tab", "tests": "tests/test_crypto_reference.py"},
    {"id": 17, "outcome": "Insecure protocol configurations",
     "feature": "Rule engine + org-configurable cipher/TLS policy engine (SecurityPolicy)",
     "api": "findings[], GET/PUT /api/admin/policy", "ui": "Findings tab; Admin -> Security Policy",
     "tests": "—"},
    {"id": 18, "outcome": "Forward secrecy", "feature": "Cipher-suite KEX classification",
     "api": "sessions[].forward_secrecy", "ui": "Session detail", "tests": "tests/test_crypto_reference.py"},
    {"id": 19, "outcome": "AI cryptographic risk scoring",
     "feature": "Hybrid rule-based (70%) + IsolationForest anomaly (30%) blend, per-reason weights",
     "api": "sessions[].risk_score, weighted_reasons, anomaly_explanation",
     "ui": "Session detail -> Risk factors (explainable)", "tests": "—"},
    {"id": 20, "outcome": "AI TLS anomaly detection", "feature": "run_anomaly_detection() (IsolationForest)",
     "api": "sessions[].anomaly_score, is_anomalous", "ui": "Session detail", "tests": "—"},
    {"id": 21, "outcome": "Prioritized security findings",
     "feature": "Severity-sorted findings with remediation tracking (open->assigned->fixed->verified)",
     "api": "findings[], PATCH /api/cases/findings/{id}/remediation", "ui": "Findings tab", "tests": "—"},
    {"id": 22, "outcome": "Comprehensive security posture",
     "feature": "Case-level grade/score rollup, historical baseline, risk trend",
     "api": "GET /api/dashboard/summary, /risk-trend, /baseline", "ui": "Dashboard", "tests": "—"},
    {"id": 23, "outcome": "JSON/PDF/HTML report + dashboard",
     "feature": "report_generator.py, evidence-hash-stamped",
     "api": "GET /api/reports/{id}/{json,pdf,html}", "ui": "Case Detail -> export buttons", "tests": "—"},
    {"id": 24, "outcome": "Evidence chain-of-custody (beyond PS text; hardening)",
     "feature": "Unified upload-hash + access/export/remediation audit trail, hash-chained",
     "api": "GET /api/cases/{id}/custody, GET /api/admin/audit-logs/verify",
     "ui": "Case Detail -> Chain of Custody tab", "tests": "tests/test_audit_chain.py"},
    {"id": 25, "outcome": "PCAP evidence viewer (beyond PS text; hardening)",
     "feature": "Per-packet metadata captured during reconstruction (packet#, ts, direction, flags, seq)",
     "api": "GET /api/cases/{id}/sessions/{sid}/packets",
     "ui": "Session detail -> Packet Evidence panel", "tests": "—"},
    {"id": 26, "outcome": "Performance benchmarking (beyond PS text; hardening)",
     "feature": "Wall-clock time + peak memory tracked per analysis run",
     "api": "GET /api/cases/benchmark", "ui": "Admin -> Performance Benchmark", "tests": "—"},
    {"id": 27, "outcome": "Role-based access control (beyond PS text; hardening)",
     "feature": "4 roles (Admin/SOC Analyst/Forensic Investigator/Compliance Officer), distinct authority",
     "api": "require_roles() on every sensitive endpoint", "ui": "Role-specific navigation & badges",
     "tests": "tests/test_rbac_matrix.py"},
]

KNOWN_LIMITATIONS = [
    "IP-level fragmentation reassembly is not implemented (TCP segmentation IS handled).",
    "Threat-intelligence enrichment (external domain/IP reputation) is deliberately not "
    "implemented -- this tool targets offline/air-gapped passive forensic analysis and a "
    "free-tier deployment.",
    "Custom compliance framework mapping is static per finding type; the cipher/TLS policy "
    "engine is the admin-editable surface for raising the bar above the built-in baseline.",
    "TCP state tracking covers FIN/RST/established, not a full RFC 793 state machine.",
    "TLS1.3 Certificate messages are encrypted by protocol design -- no passive capture "
    "(without the server's private key) can recover certificate data from a TLS1.3 session. "
    "This is a protocol property, not an implementation gap.",
]
