import json
from datetime import datetime
from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                 TableStyle, PageBreak)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from jinja2 import Template

HTML_TEMPLATE = """
<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>SecureMailScope Forensic Report — {{ case.name }}</title>
<style>
body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #1a1a2e; background:#f7f8fc;}
h1 { color: #0f172a; border-bottom: 3px solid #4f46e5; padding-bottom: 10px;}
h2 { color: #1e293b; margin-top: 32px; border-left: 4px solid #4f46e5; padding-left: 10px;}
.badge { display:inline-block; padding: 4px 12px; border-radius: 12px; color:white; font-size:12px; font-weight:600;}
.critical{background:#dc2626;} .high{background:#ea580c;} .medium{background:#d97706;} .low{background:#65a30d;} .info{background:#0284c7;}
table{ width:100%; border-collapse: collapse; margin: 16px 0; background:white; box-shadow: 0 1px 3px rgba(0,0,0,0.08);}
th, td{ text-align:left; padding: 10px 12px; border-bottom: 1px solid #e5e7eb; font-size: 13px;}
th{ background:#eef2ff; color:#3730a3;}
.summary-cards{ display:flex; gap:16px; margin:20px 0; flex-wrap:wrap;}
.card{ background:white; border-radius:10px; padding:16px 20px; box-shadow:0 1px 3px rgba(0,0,0,0.08); min-width:150px;}
.card .num{ font-size:28px; font-weight:700; color:#4f46e5;}
.card .label{ font-size:12px; color:#64748b; text-transform:uppercase; letter-spacing:0.5px;}
.finding{ background:white; border-radius:10px; padding:16px 20px; margin:12px 0; box-shadow:0 1px 3px rgba(0,0,0,0.08); border-left: 5px solid #ccc;}
.finding.critical{border-left-color:#dc2626;} .finding.high{border-left-color:#ea580c;}
.finding.medium{border-left-color:#d97706;} .finding.low{border-left-color:#65a30d;}
.rec{ background:#f0fdf4; border-radius:6px; padding:10px 14px; margin-top:8px; font-size:13px; color:#166534;}
footer{ margin-top:40px; font-size:11px; color:#94a3b8; text-align:center;}
</style></head><body>
<h1>SecureMailScope — Cryptographic Security Posture Report</h1>
<p><b>Case:</b> {{ case.name }} &nbsp; | &nbsp; <b>File:</b> {{ case.filename }} &nbsp; | &nbsp;
<b>Generated:</b> {{ generated_at }}</p>
<p style="font-size:11px; color:#64748b; font-family:monospace;">Evidence integrity — SHA-256 of original capture: {{ case.file_sha256 or "n/a" }}</p>

<div class="summary-cards">
  <div class="card"><div class="num">{{ case.overall_risk_score }}</div><div class="label">Overall Risk Score</div></div>
  <div class="card"><div class="num">{{ case.risk_grade }}</div><div class="label">Security Grade</div></div>
  <div class="card"><div class="num">{{ case.total_sessions }}</div><div class="label">Total Sessions</div></div>
  <div class="card"><div class="num">{{ case.encrypted_sessions }}</div><div class="label">Encrypted</div></div>
  <div class="card"><div class="num">{{ case.plaintext_sessions }}</div><div class="label">Plaintext</div></div>
</div>

<h2>Prioritized Findings ({{ findings|length }})</h2>
{% for f in findings %}
<div class="finding {{ f.severity }}">
  <span class="badge {{ f.severity }}">{{ f.severity|upper }}</span>
  <b>{{ f.title }}</b> <span style="color:#64748b; font-size:12px;">[{{ f.category }}]</span>
  <p>{{ f.description }}</p>
  <div class="rec"><b>Recommended mitigation:</b> {{ f.recommendation }}</div>
  <p style="font-size:11px; color:#94a3b8; margin-top:6px;">Compliance references: {{ f.compliance_refs }}</p>
</div>
{% endfor %}

<h2>Session Inventory ({{ sessions|length }})</h2>
<table>
<tr><th>Protocol</th><th>Endpoint</th><th>TLS Version</th><th>Cipher Suite</th><th>Cert Issue</th><th>Risk</th><th>Grade</th></tr>
{% for s in sessions %}
<tr>
<td>{{ s.protocol }}</td>
<td>{{ s.dst_ip }}:{{ s.dst_port }}</td>
<td>{{ s.tls_version or ("Implicit" if s.implicit_tls else "None") }}</td>
<td>{{ s.cipher_suite or "-" }}</td>
<td>{{ "Expired" if s.cert_expired else ("Self-signed" if s.cert_self_signed else "-") }}</td>
<td>{{ s.risk_score }}</td>
<td>{{ s.risk_grade }}</td>
</tr>
{% endfor %}
</table>

<footer>Generated by SecureMailScope — AI-Assisted Cryptographic Security Posture Assessment Framework.
Problem Statement 26159, National Technical Research Organisation (NTRO). For authorized security operations use only.</footer>
</body></html>
"""


def generate_json_report(case: dict, sessions: list, findings: list) -> dict:
    return {
        "report_type": "SecureMailScope Forensic Report",
        "generated_at": datetime.utcnow().isoformat(),
        "evidence_integrity": {
            "original_capture_sha256": case.get("file_sha256"),
            "note": "SHA-256 of the raw uploaded capture, computed at upload time, for "
                    "chain-of-custody verification of the source evidence.",
        },
        "case": case,
        "summary": {
            "overall_risk_score": case.get("overall_risk_score"),
            "risk_grade": case.get("risk_grade"),
            "total_sessions": case.get("total_sessions"),
            "encrypted_sessions": case.get("encrypted_sessions"),
            "plaintext_sessions": case.get("plaintext_sessions"),
            "findings_by_severity": {
                "critical": sum(1 for f in findings if f["severity"] == "critical"),
                "high": sum(1 for f in findings if f["severity"] == "high"),
                "medium": sum(1 for f in findings if f["severity"] == "medium"),
                "low": sum(1 for f in findings if f["severity"] == "low"),
            },
        },
        "sessions": sessions,
        "findings": findings,
    }


def generate_html_report(case: dict, sessions: list, findings: list) -> str:
    severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
    findings_sorted = sorted(findings, key=lambda f: severity_order.get(f["severity"], 5))
    template = Template(HTML_TEMPLATE)
    return template.render(
        case=case, sessions=sessions, findings=findings_sorted,
        generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
    )


def generate_pdf_report(case: dict, sessions: list, findings: list) -> bytes:
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=20 * mm, bottomMargin=20 * mm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleX", parent=styles["Title"], textColor=colors.HexColor("#1e1b4b"))
    h2_style = ParagraphStyle("H2X", parent=styles["Heading2"], textColor=colors.HexColor("#4f46e5"))
    body = styles["BodyText"]
    elements = []

    elements.append(Paragraph("SecureMailScope — Cryptographic Security Posture Report", title_style))
    elements.append(Spacer(1, 8))
    elements.append(Paragraph(f"Case: {case.get('name')} | File: {case.get('filename')}", body))
    elements.append(Paragraph(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", body))
    elements.append(Spacer(1, 14))

    summary_data = [
        ["Overall Risk Score", "Grade", "Total Sessions", "Encrypted", "Plaintext"],
        [str(case.get("overall_risk_score")), str(case.get("risk_grade")),
         str(case.get("total_sessions")), str(case.get("encrypted_sessions")),
         str(case.get("plaintext_sessions"))],
    ]
    t = Table(summary_data, hAlign="LEFT")
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eef2ff")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#3730a3")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 16))

    elements.append(Paragraph(f"Prioritized Findings ({len(findings)})", h2_style))
    sev_color = {"critical": "#dc2626", "high": "#ea580c", "medium": "#d97706", "low": "#65a30d"}
    severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
    for f in sorted(findings, key=lambda x: severity_order.get(x["severity"], 5)):
        color_hex = sev_color.get(f["severity"], "#64748b")
        elements.append(Paragraph(
            f'<font color="{color_hex}"><b>[{f["severity"].upper()}]</b></font> '
            f'<b>{f["title"]}</b> — <i>{f["category"]}</i>', body))
        elements.append(Paragraph(f["description"], body))
        elements.append(Paragraph(f'<b>Mitigation:</b> {f["recommendation"]}', body))
        elements.append(Paragraph(f'<font size=8 color="#94a3b8">Compliance: {f.get("compliance_refs","")}</font>', body))
        elements.append(Spacer(1, 10))

    elements.append(PageBreak())
    elements.append(Paragraph(f"Session Inventory ({len(sessions)})", h2_style))
    table_data = [["Protocol", "Endpoint", "TLS Ver", "Cipher", "Risk", "Grade"]]
    for s in sessions:
        table_data.append([
            s.get("protocol", ""), f"{s.get('dst_ip')}:{s.get('dst_port')}",
            s.get("tls_version") or ("Implicit" if s.get("implicit_tls") else "None"),
            (s.get("cipher_suite") or "-")[:28],
            str(s.get("risk_score")), s.get("risk_grade", ""),
        ])
    st = Table(table_data, repeatRows=1, hAlign="LEFT")
    st.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eef2ff")),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
        ("FONTSIZE", (0, 0), (-1, -1), 7.5),
    ]))
    elements.append(st)

    doc.build(elements)
    buf.seek(0)
    return buf.read()
